<?php

/**
 * Module File for Kala Revision Batch Delete.
 */

/**
 * Implements hook_permission().
 */
function kala_revision_batch_delete_permission() {
  return array(
    'administer kala revision batch delete' => array(
      'title' => t('Administer Kala Revision Batch Delete'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function kala_revision_batch_delete_menu() {
  $items = array();
  $items['admin/config/content/revision-batch-delete'] = array(
    'title' => 'Batch Delete Revisions',
    'description' => 'Deletes content types revisions based off a timestamp via batch.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kala_revision_batch_delete_form'),
    'access arguments' => array('administer kala revision batch delete'),
    'file' => 'includes/kala_revision_batch_delete.admin.inc',
  );
  return $items;
}
